import type {Metadata} from "next";
import "./globals.css";
import allFontsClassName from "@/constances/localFonts/allFontsClassName";
import {LAYOUT_MAX_WIDTH} from "@/constances/layout/mainLayoutExports";
import CustomToastContainer from "@/components/others/CustomToast/CustomToastContainer";
import ReactQueryProvider from "@/components/ClientComponents/ReactQueryProvider";
import React from "react";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body
      style={{
        backgroundImage: `url('/background.svg')`,
        backgroundRepeat: 'repeat',
        // zIndex: 10,
      }}
      className={`
        ${allFontsClassName} antialiased bg-gray-2 font-kook rtl text-foreground ${LAYOUT_MAX_WIDTH}
      `}
    >
    <CustomToastContainer/>

    <ReactQueryProvider>
      <div className={`
        flex flex-col absolute inset-0 h-full w-full z-10 ${LAYOUT_MAX_WIDTH}
      `}>


        <div className={`
         h-full w-full
      `}>
          {children}
        </div>
      </div>
    </ReactQueryProvider>
    </body>
    </html>
  );
}
