import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import allFontsClassName from "@/constances/localFonts/allFontsClassName";
import {LAYOUT_MAX_WIDTH} from "@/constances/layout/mainLayoutExports";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body
      style={{
        backgroundImage: `url('/background.svg')`,
        backgroundRepeat: 'repeat',
        // zIndex: 10,
        backgroundColor: '#F2F1ED'
      }}
      className={`
        ${allFontsClassName} antialiased font-kook rtl text-foreground ${LAYOUT_MAX_WIDTH}
      `}
    >
        {children}
      </body>
    </html>
  );
}
